services:
  serve:
    build: &default-build-spec
      context: .
      dockerfile: Dockerfile
      target: serve
    network_mode: "host"
    environment:
      - SPRING83_FQDN=${SPRING83_FQDN}
    volumes: &default-logs-bind
      - type: bind
        source: ${SPRING83_CONTENT_DIR_HOST:?"Must define SPRING83_CONTENT_DIR_HOST as the absolute path to logs on the host."}
        target: /content

volumes:
  content:
    external: true